### PR TITLE
Google App Engine Deployment

### PR DESCRIPTION
**Pull request by rodartecode**
Still working on this, but the setup is a 'dev' environment that's run whenever you run the app locally, and a 'cloud' environment when the app detects that it is running on GAE. Doing the set up to deploy on GAE is pretty extensive, but this shouldn't have any effects on running the app locally.

Going to keep working on it and update if I manage a stable and consistent deployment.

### CODE REVIEW

**Comment by rodartecode** [comment]
A huge chunk of the additions are just modules needed for deployment. I only made a few changes to our working files.

**Comment by rodartecode** [comment]
Oh right, and there's also the google OAuth stuff I added, is that something we want to keep?

**Comment by MissValeska** [comment]
Well, we need to have a method of securing access to the google database. We do not want anyone to be able to access anyone else's dataset via url manipulation, postman, etc just because the database doesn't take authentication. So, I think we need something of a JWT access token perhaps from our backend which is sent to the remote google database to secure access from user 1 to user 1's data and only that person's data. this may be complicated though, I was having trouble with this before.

**Comment by rodartecode** [comment]
I think we're fine regarding security for `prod` because the only way to make a request to the google DB is by being signed in (like directly signed into the DB via SSH) or having a key. The way its setup right now is the backend only makes requests that are contextualized to the current signed in user. If a user isn't signed in they wouldn't make it far enough to make a request. In order for a URL manipulation or postman request to work they would already need a signed url, which they can't make without the secret access codes. 

Or am I missing something else?

**Comment by MissValeska** [comment]
okay, that makes sense. So, then, since the back-end is the only place that decides which user's data is being accessed and the front-end has no access to the back-end, no one from the front-end can access anyone else's DB results? Does the javascript console ever print the url for the google database?

**Pull request merged**
